import streamlit as st
import requests
import datetime

# --- Backend URL ---
BASE_URL = "http://localhost:8000"  # Make sure FastAPI is running here

# --- Page Configuration ---
st.set_page_config(
    page_title="🌏 GoBot: Agentic-AI Travel Planner",
    page_icon="🌏",
    layout="centered",
    initial_sidebar_state="expanded",
)

# --- App Title and Subtitle ---
st.markdown("<h2 style='text-align: center;'>🌏🏝️🏔️ GoBot: Agentic-AI Travel Planner</h2>", unsafe_allow_html=True)
st.markdown("<h4 style='text-align: center; color: grey;'>Let GoBot help you plan your perfect trip!</h4>", unsafe_allow_html=True)
st.markdown("---")

# --- Chat Prompt ---
st.markdown("#### ✈️ Out of all the places in the world, where would you like to go?")
st.info("Help me with your dream destination and trip duration. For example: **Plan a trip to Munich for 5 days**.")

# --- Initialize session state ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# --- Input Form ---
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input(
        "📝 Travel Requests:",
        placeholder="e.g. Plan a romantic 3-day trip to Paris with sightseeing and food recommendations",
    )
    submit_button = st.form_submit_button("🛰️ Generate Plan")

# --- Handle Submission ---
if submit_button and user_input.strip():
    try:
        with st.spinner("🤖 Generating your personalized travel plan..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            st.success("✅ Here is your travel plan!")

            # --- Display Travel Plan ---
            st.markdown(f"""
<div style="background-color: #f9f9f9; padding: 20px; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.05);">
<h3>📅 Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}</h3>
<p style="font-size: 16px;">{answer}</p>
<hr />
<p style="color: grey; font-size: 14px;">
⚠️ <i>This travel plan was generated by AI. Please double-check all details (e.g. prices, hours, travel restrictions) before booking!</i>
</p>
</div>
""", unsafe_allow_html=True)

        else:
            st.error(f"❌ Bot failed to respond: {response.status_code}\n\n{response.text}")

    except Exception as e:
        st.error(f"❌ The response failed due to:\n\n{e}")

# --- Footer ---
st.markdown("---")
st.markdown("<p style='text-align: center; color: grey;'>Trinita's AI Travel Agent ✈️</p>", unsafe_allow_html=True)
